#!/bin/bash
FILE="${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS%?}"
if [ $(xdg-mime query filetype "$FILE" | cut -d '/' -f 1) = "image" ];then
    # OUTPUT=$(swaymsg -t get_outputs | jq -r '.[].name')
    OUTPUT="$(wlr-randr | grep -o '^[A-Za-z\-]*-[0-9]')"
    if [ $(echo "$OUTPUT" | wc -w ) != "1" ];then
        OUTPUT=$(echo "$OUTPUT" | rofi -dmenu -p '>')
    fi
    if [ -n "$OUTPUT" ]; then
        if [ ! -e ~/.local/share/backgrounds ]; then
            mkdir -p ~/.local/share/backgrounds
        fi
        cp "${FILE}" ~/.local/share/backgrounds/"$OUTPUT"
      swaybg -o "$OUTPUT" -i ~/.local/share/backgrounds/"$OUTPUT" -m fill
    fi
fi
