snippet_support = true
verbosity = 2
[semantic_scopes]
  variable = "variable"
  entity_name_function = "function"
  entity_name_type = "type"
  variable_other_enummember = "variable"
  entity_name_namespace = "module"
[semantic_tokens]
  type = "type"
  variable = "variable"
  namespace = "module"
  function = "function"
  string = "string"
  keyword = "keyword"
  operator = "operator"
  comment = "comment"
[semantic_modifiers]
  documentation = "documentation"
  readonly = "default+d"
[server]
# exit session if no requests were received during given period in seconds
# works only in unix sockets mode (-s/--session)
# set to 0 to disable
timeout = 1800 # seconds = 30 minutes


[language.rust]
  filetypes = ["rust"]
  roots = ["Cargo.toml"]
  command = "rust-analyzer"
[language.c_cpp]
  filetypes = ["c", "cpp"]
  roots = ["compile_commands.json", ".clangd"]
  command = "clangd"
